package commandcensus

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

// S1BootstrapCatalog is the exact pre-generator catalog accepted for the initial migration.
const S1BootstrapCatalog = `package productmetrics

// generatedCommandIDCatalog is the concrete empty S1 command-census seam.
// S9 replaces this file with generated, typed yield calls; callers continue to
// consume the same immutable function-backed catalog.
func generatedCommandIDCatalog(func(commandIDEntry)) {}
`

// Artifacts contains all deterministic outputs generated from a command-census manifest.
type Artifacts struct {
	RuntimeGo  string
	CatalogGo  string
	SchemaJSON string
}

// AllocationLedger records every generated command identity and the next available ID.
type AllocationLedger struct {
	NextID     uint16     `json:"next_id"`
	Identities []Identity `json:"identities"`
	Bootstrap  bool       `json:"-"`
}

// GenerateArtifacts validates a manifest and renders its runtime, catalog, and schema outputs.
func GenerateArtifacts(manifest Manifest, schema []byte) (Artifacts, error) {
	if err := ValidateManifest(manifest); err != nil {
		return Artifacts{}, err
	}
	identities := generatedIdentities(manifest)
	runtimeGo, err := renderRuntimeGo(manifest, identities)
	if err != nil {
		return Artifacts{}, err
	}
	catalogGo, err := renderCatalogGo(manifest, identities)
	if err != nil {
		return Artifacts{}, err
	}
	schemaJSON, err := renderSchema(schema, manifest, identities)
	if err != nil {
		return Artifacts{}, err
	}
	return Artifacts{RuntimeGo: runtimeGo, CatalogGo: catalogGo, SchemaJSON: schemaJSON}, nil
}

func generatedIdentities(manifest Manifest) []Identity {
	byID := make(map[uint16]Identity)
	for _, command := range append(append([]Command(nil), manifest.Commands...), manifest.Synthetic...) {
		if command.RecordingPolicy != RecordingRecordable || command.ID < 5 {
			continue
		}
		if _, exists := byID[command.ID]; !exists {
			byID[command.ID] = Identity{Name: command.Classification, ID: command.ID, Wire: command.Classification}
		}
	}
	for _, tombstone := range manifest.Tombstones {
		byID[tombstone.ID] = Identity{Name: tombstone.Name, ID: tombstone.ID, Wire: tombstone.Wire, Retired: true}
	}
	identities := make([]Identity, 0, len(byID))
	for _, identity := range byID {
		identities = append(identities, identity)
	}
	sort.Slice(identities, func(i, j int) bool { return identities[i].ID < identities[j].ID })
	return identities
}

func renderRuntimeGo(manifest Manifest, identities []Identity) (string, error) {
	var out strings.Builder
	out.WriteString("// Code generated by gen-command-census; DO NOT EDIT.\n\npackage main\n\n")
	if len(identities) > 0 {
		out.WriteString("const (\n")
		for _, identity := range identities {
			if isTombstone(manifest, identity.ID) {
				continue
			}
			fmt.Fprintf(&out, "\tproductMetricsGeneratedCommandID%d productMetricsCommandID = %d\n", identity.ID, identity.ID)
		}
		out.WriteString(")\n\n")
	}
	out.WriteString("var generatedProductMetricsGlobalConditionalModes = []productMetricsConditionalMode{")
	for index, mode := range manifest.GlobalConditionalModes {
		if index > 0 {
			out.WriteString(", ")
		}
		out.WriteString(conditionalExpr(mode))
	}
	out.WriteString("}\n\n")
	out.WriteString("var generatedProductMetricsCommandCensus = []productMetricsCommandCensusEntry{\n")
	for _, command := range manifest.Commands {
		writeRuntimeRow(&out, command)
	}
	out.WriteString("}\n\nvar generatedProductMetricsSyntheticCensus = []productMetricsSyntheticCensusEntry{\n")
	for _, command := range manifest.Synthetic {
		writeRuntimeRow(&out, command)
	}
	out.WriteString("}\n")
	return formatGo(out.String())
}

func writeRuntimeRow(out *strings.Builder, command Command) {
	fmt.Fprintf(out, "\t{Path: %s, Aliases: %s, ConditionalModes: %s, Hidden: %t, EffectiveHidden: %t, DisableFlagParsing: %t, Shape: %s, Classification: %s, Mode: %s, Notice: %s, Recording: %s, Owner: %s",
		strconv.Quote(command.Path), renderStringSlice(command.Aliases), renderConditionalModes(command.ConditionalModes), command.Hidden, command.EffectiveHidden, command.DisableFlagParsing,
		shapeExpr(command.Shape), strconv.Quote(command.Classification), modeExpr(command.Mode), noticeExpr(command.NoticePolicy), recordingExpr(command.RecordingPolicy), ownerExpr(command.Owner))
	if command.Resolver != "" {
		fmt.Fprintf(out, ", Resolver: %s", resolverExpr(command.Resolver))
	}
	if command.Exclusion != "" {
		fmt.Fprintf(out, ", Exclusion: %s", exclusionExpr(command.Exclusion))
	}
	if command.DeferredDefault != "" {
		fmt.Fprintf(out, ", DeferredDefault: %s", deferredExpr(command.DeferredDefault))
	}
	if command.ID != 0 {
		fmt.Fprintf(out, ", ID: %s", runtimeIDExpr(command.ID))
	}
	out.WriteString("},\n")
}

func renderCatalogGo(manifest Manifest, identities []Identity) (string, error) {
	var out strings.Builder
	out.WriteString("// Code generated by gen-command-census; DO NOT EDIT.\n\npackage productmetrics\n\n")
	ledgerJSON, _ := json.Marshal(AllocationLedger{NextID: manifest.NextID, Identities: identities})
	fmt.Fprintf(&out, "// command-census-ledger: %s\n", ledgerJSON)
	if len(identities) > 0 {
		out.WriteString("\nconst (\n")
		for _, identity := range identities {
			fmt.Fprintf(&out, "\tgeneratedCommandID%d CommandID = %d\n", identity.ID, identity.ID)
		}
		out.WriteString(")\n")
	}
	out.WriteString("\nfunc generatedCommandIDCatalog(yield func(commandIDEntry)) {\n")
	for _, identity := range identities {
		fmt.Fprintf(&out, "\tyield(commandIDEntry{id: generatedCommandID%d, wire: %s})\n", identity.ID, strconv.Quote(identity.Wire))
	}
	out.WriteString("}\n")
	return formatGo(out.String())
}

func renderSchema(schema []byte, manifest Manifest, identities []Identity) (string, error) {
	wires := make([]string, 0, int(manifest.NextID)-1)
	wires = append(wires, "help", "version", "unknown", "pack-command")
	for _, identity := range identities {
		wires = append(wires, identity.Wire)
	}
	root, commandID, err := decodeSchemaCommandIDPath(schema)
	if err != nil {
		return "", err
	}
	commandID["enum"] = wires
	updated, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return "", fmt.Errorf("command census: encode schema: %w", err)
	}
	return string(updated) + "\n", nil
}

// ParseGeneratedAllocationLedger reads the append-only allocation ledger embedded in a generated catalog.
func ParseGeneratedAllocationLedger(data []byte) (AllocationLedger, error) {
	if string(data) == S1BootstrapCatalog {
		return AllocationLedger{Bootstrap: true}, nil
	}
	const prefix = "// command-census-ledger: "
	var payload []byte
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "// command-census-") {
			if !strings.HasPrefix(line, prefix) || payload != nil {
				return AllocationLedger{}, fmt.Errorf("command census: malformed or duplicate ledger marker %q", line)
			}
			payload = []byte(strings.TrimPrefix(line, prefix))
		}
	}
	if payload == nil {
		return AllocationLedger{}, fmt.Errorf("command census: existing catalog has no allocation ledger")
	}
	if err := rejectDuplicateJSONKeys(payload); err != nil {
		return AllocationLedger{}, fmt.Errorf("command census: invalid allocation ledger: %w", err)
	}
	decoder := json.NewDecoder(bytes.NewReader(payload))
	decoder.DisallowUnknownFields()
	var ledger AllocationLedger
	if err := decoder.Decode(&ledger); err != nil {
		return AllocationLedger{}, fmt.Errorf("command census: invalid allocation ledger: %w", err)
	}
	if err := requireJSONEOF(decoder); err != nil {
		return AllocationLedger{}, fmt.Errorf("command census: invalid allocation ledger: %w", err)
	}
	var rawLedger struct {
		Identities []map[string]json.RawMessage `json:"identities"`
	}
	if err := json.Unmarshal(payload, &rawLedger); err != nil {
		return AllocationLedger{}, err
	}
	for index, identity := range rawLedger.Identities {
		retiredJSON, present := identity["retired"]
		if !present {
			return AllocationLedger{}, fmt.Errorf("command census: allocation ledger identity %d is missing retired state", index)
		}
		var retired *bool
		if err := json.Unmarshal(retiredJSON, &retired); err != nil || retired == nil {
			return AllocationLedger{}, fmt.Errorf("command census: allocation ledger identity %d has invalid retired state", index)
		}
	}
	if ledger.NextID < 5 || ledger.Identities == nil || len(ledger.Identities) != int(ledger.NextID)-5 {
		return AllocationLedger{}, fmt.Errorf("command census: allocation ledger is not gapless through next_id %d", ledger.NextID)
	}
	seenNames, seenWires := make(map[string]struct{}), make(map[string]struct{})
	for index, identity := range ledger.Identities {
		wantID := uint16(index + 5)
		if identity.ID != wantID || !validWire(identity.Name) || !validWire(identity.Wire) {
			return AllocationLedger{}, fmt.Errorf("command census: invalid allocation ledger identity %+v, want id %d", identity, wantID)
		}
		if _, duplicate := seenNames[identity.Name]; duplicate {
			return AllocationLedger{}, fmt.Errorf("command census: duplicate allocation name %q", identity.Name)
		}
		if _, duplicate := seenWires[identity.Wire]; duplicate {
			return AllocationLedger{}, fmt.Errorf("command census: duplicate allocation wire %q", identity.Wire)
		}
		seenNames[identity.Name], seenWires[identity.Wire] = struct{}{}, struct{}{}
	}
	return ledger, nil
}

// ValidateEvolution rejects removal, reuse, or reactivation of prior command allocations.
func ValidateEvolution(previous AllocationLedger, current Manifest) error {
	if previous.Bootstrap {
		return nil
	}
	if current.NextID < previous.NextID {
		return fmt.Errorf("command census: next_id decreased from %d to %d", previous.NextID, current.NextID)
	}
	currentByID := make(map[uint16]Identity)
	currentByWire := make(map[string]Identity)
	identities := generatedIdentities(current)
	for _, identity := range identities {
		currentByID[identity.ID] = identity
		currentByWire[identity.Wire] = identity
	}
	for _, old := range previous.Identities {
		byID, idOK := currentByID[old.ID]
		byWire, wireOK := currentByWire[old.Wire]
		if !idOK || !wireOK || byID.Wire != old.Wire || byWire.ID != old.ID || byID.Name != old.Name || (old.Retired && !byID.Retired) {
			return fmt.Errorf("command census: prior allocation id=%d wire=%q was removed or remapped; retain it as a tombstone", old.ID, old.Wire)
		}
	}
	return nil
}

func decodeSchemaCommandIDPath(schema []byte) (map[string]any, map[string]any, error) {
	if err := rejectDuplicateJSONKeys(schema); err != nil {
		return nil, nil, fmt.Errorf("command census: invalid schema JSON: %w", err)
	}
	var root map[string]any
	decoder := json.NewDecoder(bytes.NewReader(schema))
	decoder.UseNumber()
	if err := decoder.Decode(&root); err != nil {
		return nil, nil, fmt.Errorf("command census: decode schema: %w", err)
	}
	if err := requireJSONEOF(decoder); err != nil {
		return nil, nil, fmt.Errorf("command census: decode schema: %w", err)
	}
	current := any(root)
	for _, key := range []string{"properties", "events", "items", "properties", "command_id"} {
		object, ok := current.(map[string]any)
		if !ok {
			return nil, nil, fmt.Errorf("command census: schema path to command_id is not an object at %q", key)
		}
		current, ok = object[key]
		if !ok {
			return nil, nil, fmt.Errorf("command census: schema path is missing %q", key)
		}
	}
	commandID, ok := current.(map[string]any)
	if !ok {
		return nil, nil, fmt.Errorf("command census: command_id schema is not an object")
	}
	if _, ok := commandID["enum"].([]any); !ok {
		return nil, nil, fmt.Errorf("command census: command_id enum is missing or not an array")
	}
	return root, commandID, nil
}

func isTombstone(manifest Manifest, id uint16) bool {
	for _, tombstone := range manifest.Tombstones {
		if tombstone.ID == id {
			return true
		}
	}
	return false
}

func goIdentifier(value string) string {
	var result strings.Builder
	upperNext := true
	for _, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upperNext = true
			continue
		}
		if upperNext {
			r = unicode.ToUpper(r)
			upperNext = false
		}
		result.WriteRune(r)
	}
	return result.String()
}

func formatGo(source string) (string, error) {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return "", fmt.Errorf("command census: format generated Go: %w\n%s", err, source)
	}
	return string(formatted), nil
}

func renderStringSlice(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = strconv.Quote(value)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func renderConditionalModes(values []ConditionalMode) string {
	expressions := make([]string, len(values))
	for index, value := range values {
		expressions[index] = conditionalExpr(value)
	}
	return "[]productMetricsConditionalMode{" + strings.Join(expressions, ", ") + "}"
}

func shapeExpr(value Shape) string { return "productMetricsShape" + goIdentifier(string(value)) }
func modeExpr(value Mode) string   { return "productMetricsMode" + goIdentifier(string(value)) }
func noticeExpr(value NoticePolicy) string {
	return "productMetricsNotice" + goIdentifier(string(value))
}

func recordingExpr(value RecordingPolicy) string {
	return "productMetricsRecording" + goIdentifier(string(value))
}
func ownerExpr(value Owner) string { return "productMetricsOwner" + goIdentifier(string(value)) }
func exclusionExpr(value Exclusion) string {
	return "productMetricsExclusion" + goIdentifier(string(value))
}

func deferredExpr(value DeferredDefault) string {
	return "productMetricsDeferred" + goIdentifier(string(value))
}
func resolverExpr(value string) string { return "productMetricsResolver" + goIdentifier(value) }
func conditionalExpr(value ConditionalMode) string {
	return "productMetricsConditional" + goIdentifier(string(value))
}

func runtimeIDExpr(id uint16) string {
	switch id {
	case 1:
		return "productMetricsCommandHelp"
	case 2:
		return "productMetricsCommandVersion"
	case 3:
		return "productMetricsCommandUnknown"
	case 4:
		return "productMetricsCommandPackCommand"
	default:
		return fmt.Sprintf("productMetricsGeneratedCommandID%d", id)
	}
}
